### ISSUE TITLE
Multiple Layer

### ISSUE THREAD

**Issue by Veaullus** [JackDougherty/FusionTable-Map-2-layers#26]
Hello,

I posted a request on the "derekeder/FusionTable-Map-Template ".
(derekeder/FusionTable-Map-Template).
And he send me here.

I wonder how to deal with multiple "point layers".
I managed to display 4 points-layers, but no success with the checkbox to (en)able visibility or to include those layers in the "search" tool.

Sorry for my English ;-)
And sorry if this kind of ask for helping is not "GitHub" friendly. I just landed here on GitHub.

Thank you.

**Comment by JackDougherty** [comment]
Hi Veaullus

Here are two suggestions:

1) For a general tutorial about the Fusion Table Map Template, see http://www.datavizbook.org/content/map/searchable-gft-ghpages/tutorial.html
It shows how to fork and share your code in GitHub. This makes your work visible to other people in case you need help.

2) To display multiple point layers using check boxes, in this 2-layer template see this part of the HTML file:
https://github.com/JackDougherty/FusionTable-Map-2-layers/blob/master/index.html#L65

and also this part of the JS file:
https://github.com/JackDougherty/FusionTable-Map-2-layers/blob/master/js/maps_lib.js#L137

My 2-layer template is not current with Derek's general template. So they will have differences.

hope that helps
Jack
